// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: cmd/pb/core.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Result_Type int32

const (
	Result_succeeded Result_Type = 0
	Result_failed    Result_Type = 1
)

// Enum value maps for Result_Type.
var (
	Result_Type_name = map[int32]string{
		0: "succeeded",
		1: "failed",
	}
	Result_Type_value = map[string]int32{
		"succeeded": 0,
		"failed":    1,
	}
)

func (x Result_Type) Enum() *Result_Type {
	p := new(Result_Type)
	*p = x
	return p
}

func (x Result_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_pb_core_proto_enumTypes[0].Descriptor()
}

func (Result_Type) Type() protoreflect.EnumType {
	return &file_cmd_pb_core_proto_enumTypes[0]
}

func (x Result_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result_Type.Descriptor instead.
func (Result_Type) EnumDescriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{1, 0}
}

type CommandExecuteResult_Type int32

const (
	CommandExecuteResult_succeeded CommandExecuteResult_Type = 0
	CommandExecuteResult_failed    CommandExecuteResult_Type = 1
	CommandExecuteResult_stdout    CommandExecuteResult_Type = 2
	CommandExecuteResult_stderr    CommandExecuteResult_Type = 3
)

// Enum value maps for CommandExecuteResult_Type.
var (
	CommandExecuteResult_Type_name = map[int32]string{
		0: "succeeded",
		1: "failed",
		2: "stdout",
		3: "stderr",
	}
	CommandExecuteResult_Type_value = map[string]int32{
		"succeeded": 0,
		"failed":    1,
		"stdout":    2,
		"stderr":    3,
	}
)

func (x CommandExecuteResult_Type) Enum() *CommandExecuteResult_Type {
	p := new(CommandExecuteResult_Type)
	*p = x
	return p
}

func (x CommandExecuteResult_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandExecuteResult_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_pb_core_proto_enumTypes[1].Descriptor()
}

func (CommandExecuteResult_Type) Type() protoreflect.EnumType {
	return &file_cmd_pb_core_proto_enumTypes[1]
}

func (x CommandExecuteResult_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandExecuteResult_Type.Descriptor instead.
func (CommandExecuteResult_Type) EnumDescriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{3, 0}
}

type ReloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigFilePath string `protobuf:"bytes,1,opt,name=config_file_path,json=configFilePath,proto3" json:"config_file_path,omitempty"`
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_pb_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_pb_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{0}
}

func (x *ReloadRequest) GetConfigFilePath() string {
	if x != nil {
		return x.ConfigFilePath
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    Result_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Result_Type" json:"type,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_pb_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_pb_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetType() Result_Type {
	if x != nil {
		return x.Type
	}
	return Result_succeeded
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *CommandExecuteRequest) Reset() {
	*x = CommandExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_pb_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecuteRequest) ProtoMessage() {}

func (x *CommandExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_pb_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecuteRequest.ProtoReflect.Descriptor instead.
func (*CommandExecuteRequest) Descriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{2}
}

func (x *CommandExecuteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommandExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandExecuteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    CommandExecuteResult_Type `protobuf:"varint,2,opt,name=type,proto3,enum=pb.CommandExecuteResult_Type" json:"type,omitempty"`
	Payload string                    `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CommandExecuteResult) Reset() {
	*x = CommandExecuteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_pb_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecuteResult) ProtoMessage() {}

func (x *CommandExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_pb_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecuteResult.ProtoReflect.Descriptor instead.
func (*CommandExecuteResult) Descriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{3}
}

func (x *CommandExecuteResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommandExecuteResult) GetType() CommandExecuteResult_Type {
	if x != nil {
		return x.Type
	}
	return CommandExecuteResult_succeeded
}

func (x *CommandExecuteResult) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type DaemonCommandListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DaemonCommandListRequest) Reset() {
	*x = DaemonCommandListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_pb_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonCommandListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonCommandListRequest) ProtoMessage() {}

func (x *DaemonCommandListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_pb_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonCommandListRequest.ProtoReflect.Descriptor instead.
func (*DaemonCommandListRequest) Descriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{4}
}

type DaemonCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Usage    string   `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Aliases  []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Category string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *DaemonCommand) Reset() {
	*x = DaemonCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_pb_core_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonCommand) ProtoMessage() {}

func (x *DaemonCommand) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_pb_core_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonCommand.ProtoReflect.Descriptor instead.
func (*DaemonCommand) Descriptor() ([]byte, []int) {
	return file_cmd_pb_core_proto_rawDescGZIP(), []int{5}
}

func (x *DaemonCommand) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DaemonCommand) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *DaemonCommand) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *DaemonCommand) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_cmd_pb_core_proto protoreflect.FileDescriptor

var file_cmd_pb_core_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x39, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x6a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x22, 0x3b,
	0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x14,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x39, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x10, 0x03, 0x22, 0x1a, 0x0a, 0x18,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6f, 0x0a, 0x0d, 0x44, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0xd7, 0x01, 0x0a, 0x0d, 0x44, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x2f, 0x0a, 0x0c, 0x52,
	0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x19,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x66, 0x61, 0x62, 0x72,
	0x69, 0x63, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cmd_pb_core_proto_rawDescOnce sync.Once
	file_cmd_pb_core_proto_rawDescData = file_cmd_pb_core_proto_rawDesc
)

func file_cmd_pb_core_proto_rawDescGZIP() []byte {
	file_cmd_pb_core_proto_rawDescOnce.Do(func() {
		file_cmd_pb_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_pb_core_proto_rawDescData)
	})
	return file_cmd_pb_core_proto_rawDescData
}

var file_cmd_pb_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cmd_pb_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cmd_pb_core_proto_goTypes = []interface{}{
	(Result_Type)(0),                 // 0: pb.Result.Type
	(CommandExecuteResult_Type)(0),   // 1: pb.CommandExecuteResult.Type
	(*ReloadRequest)(nil),            // 2: pb.ReloadRequest
	(*Result)(nil),                   // 3: pb.Result
	(*CommandExecuteRequest)(nil),    // 4: pb.CommandExecuteRequest
	(*CommandExecuteResult)(nil),     // 5: pb.CommandExecuteResult
	(*DaemonCommandListRequest)(nil), // 6: pb.DaemonCommandListRequest
	(*DaemonCommand)(nil),            // 7: pb.DaemonCommand
}
var file_cmd_pb_core_proto_depIdxs = []int32{
	0, // 0: pb.Result.type:type_name -> pb.Result.Type
	1, // 1: pb.CommandExecuteResult.type:type_name -> pb.CommandExecuteResult.Type
	2, // 2: pb.DaemonControl.ReloadConfig:input_type -> pb.ReloadRequest
	4, // 3: pb.DaemonControl.ExecuteCommand:input_type -> pb.CommandExecuteRequest
	6, // 4: pb.DaemonControl.GetDaemonCommands:input_type -> pb.DaemonCommandListRequest
	3, // 5: pb.DaemonControl.ReloadConfig:output_type -> pb.Result
	5, // 6: pb.DaemonControl.ExecuteCommand:output_type -> pb.CommandExecuteResult
	7, // 7: pb.DaemonControl.GetDaemonCommands:output_type -> pb.DaemonCommand
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_pb_core_proto_init() }
func file_cmd_pb_core_proto_init() {
	if File_cmd_pb_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_pb_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_pb_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_pb_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_pb_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandExecuteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_pb_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonCommandListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_pb_core_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_pb_core_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_pb_core_proto_goTypes,
		DependencyIndexes: file_cmd_pb_core_proto_depIdxs,
		EnumInfos:         file_cmd_pb_core_proto_enumTypes,
		MessageInfos:      file_cmd_pb_core_proto_msgTypes,
	}.Build()
	File_cmd_pb_core_proto = out.File
	file_cmd_pb_core_proto_rawDesc = nil
	file_cmd_pb_core_proto_goTypes = nil
	file_cmd_pb_core_proto_depIdxs = nil
}
