// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control/rpc/pb/core.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SeedPeerRequest struct {
	Network              string                              `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Endpoint             []*SeedPeerRequest_EndpointIdentity `protobuf:"bytes,2,rep,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *SeedPeerRequest) Reset()         { *m = SeedPeerRequest{} }
func (m *SeedPeerRequest) String() string { return proto.CompactTextString(m) }
func (*SeedPeerRequest) ProtoMessage()    {}
func (*SeedPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fe1d566e4e51bf9, []int{0}
}

func (m *SeedPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeedPeerRequest.Unmarshal(m, b)
}
func (m *SeedPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeedPeerRequest.Marshal(b, m, deterministic)
}
func (m *SeedPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeedPeerRequest.Merge(m, src)
}
func (m *SeedPeerRequest) XXX_Size() int {
	return xxx_messageInfo_SeedPeerRequest.Size(m)
}
func (m *SeedPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeedPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeedPeerRequest proto.InternalMessageInfo

func (m *SeedPeerRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *SeedPeerRequest) GetEndpoint() []*SeedPeerRequest_EndpointIdentity {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type SeedPeerRequest_EndpointIdentity struct {
	EndpointType         string   `protobuf:"bytes,1,opt,name=endpoint_type,json=endpointType,proto3" json:"endpoint_type,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeedPeerRequest_EndpointIdentity) Reset()         { *m = SeedPeerRequest_EndpointIdentity{} }
func (m *SeedPeerRequest_EndpointIdentity) String() string { return proto.CompactTextString(m) }
func (*SeedPeerRequest_EndpointIdentity) ProtoMessage()    {}
func (*SeedPeerRequest_EndpointIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fe1d566e4e51bf9, []int{0, 0}
}

func (m *SeedPeerRequest_EndpointIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeedPeerRequest_EndpointIdentity.Unmarshal(m, b)
}
func (m *SeedPeerRequest_EndpointIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeedPeerRequest_EndpointIdentity.Marshal(b, m, deterministic)
}
func (m *SeedPeerRequest_EndpointIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeedPeerRequest_EndpointIdentity.Merge(m, src)
}
func (m *SeedPeerRequest_EndpointIdentity) XXX_Size() int {
	return xxx_messageInfo_SeedPeerRequest_EndpointIdentity.Size(m)
}
func (m *SeedPeerRequest_EndpointIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SeedPeerRequest_EndpointIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SeedPeerRequest_EndpointIdentity proto.InternalMessageInfo

func (m *SeedPeerRequest_EndpointIdentity) GetEndpointType() string {
	if m != nil {
		return m.EndpointType
	}
	return ""
}

func (m *SeedPeerRequest_EndpointIdentity) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type SetNetworkRequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Start                bool     `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNetworkRequest) Reset()         { *m = SetNetworkRequest{} }
func (m *SetNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*SetNetworkRequest) ProtoMessage()    {}
func (*SetNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fe1d566e4e51bf9, []int{1}
}

func (m *SetNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNetworkRequest.Unmarshal(m, b)
}
func (m *SetNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNetworkRequest.Marshal(b, m, deterministic)
}
func (m *SetNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNetworkRequest.Merge(m, src)
}
func (m *SetNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_SetNetworkRequest.Size(m)
}
func (m *SetNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetNetworkRequest proto.InternalMessageInfo

func (m *SetNetworkRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *SetNetworkRequest) GetStart() bool {
	if m != nil {
		return m.Start
	}
	return false
}

type ReloadRequest struct {
	ConfigFilePath       string   `protobuf:"bytes,1,opt,name=config_file_path,json=configFilePath,proto3" json:"config_file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadRequest) Reset()         { *m = ReloadRequest{} }
func (m *ReloadRequest) String() string { return proto.CompactTextString(m) }
func (*ReloadRequest) ProtoMessage()    {}
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fe1d566e4e51bf9, []int{2}
}

func (m *ReloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadRequest.Unmarshal(m, b)
}
func (m *ReloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadRequest.Marshal(b, m, deterministic)
}
func (m *ReloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadRequest.Merge(m, src)
}
func (m *ReloadRequest) XXX_Size() int {
	return xxx_messageInfo_ReloadRequest.Size(m)
}
func (m *ReloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadRequest proto.InternalMessageInfo

func (m *ReloadRequest) GetConfigFilePath() string {
	if m != nil {
		return m.ConfigFilePath
	}
	return ""
}

type Result struct {
	Succeed              bool     `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fe1d566e4e51bf9, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SeedPeerRequest)(nil), "pb.SeedPeerRequest")
	proto.RegisterType((*SeedPeerRequest_EndpointIdentity)(nil), "pb.SeedPeerRequest.EndpointIdentity")
	proto.RegisterType((*SetNetworkRequest)(nil), "pb.SetNetworkRequest")
	proto.RegisterType((*ReloadRequest)(nil), "pb.ReloadRequest")
	proto.RegisterType((*Result)(nil), "pb.Result")
}

func init() { proto.RegisterFile("control/rpc/pb/core.proto", fileDescriptor_1fe1d566e4e51bf9) }

var fileDescriptor_1fe1d566e4e51bf9 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xb5, 0x18, 0xb1, 0x8e, 0xa0, 0xb0, 0x6a, 0x82, 0x9c, 0x48, 0xf5, 0xc0, 0xc5, 0x36, 0xe2,
	0xc9, 0xc4, 0x83, 0x09, 0xd1, 0xc4, 0x83, 0x86, 0x14, 0xef, 0x64, 0xdb, 0x0e, 0xd0, 0x58, 0x76,
	0xd7, 0xed, 0x10, 0xc3, 0x07, 0xf9, 0x23, 0x7e, 0x99, 0xa1, 0xdb, 0x45, 0x69, 0x4c, 0x3c, 0xbe,
	0x79, 0xfb, 0xde, 0x9b, 0x79, 0x59, 0x38, 0x8f, 0xa5, 0x20, 0x2d, 0xb3, 0x40, 0xab, 0x38, 0x50,
	0x51, 0x10, 0x4b, 0x8d, 0xbe, 0xd2, 0x92, 0x24, 0xab, 0xa9, 0xc8, 0xfb, 0x72, 0xe0, 0x78, 0x8c,
	0x98, 0x8c, 0x10, 0x75, 0x88, 0xef, 0x4b, 0xcc, 0x89, 0x75, 0x60, 0x5f, 0x20, 0x7d, 0x48, 0xfd,
	0xd6, 0x71, 0x7a, 0x4e, 0xff, 0x20, 0xb4, 0x90, 0xdd, 0x83, 0x8b, 0x22, 0x51, 0x32, 0x15, 0xd4,
	0xa9, 0xf5, 0x76, 0xfb, 0x87, 0x83, 0x4b, 0x5f, 0x45, 0x7e, 0xc5, 0xc0, 0x7f, 0x28, 0xdf, 0x3c,
	0x25, 0x28, 0x28, 0xa5, 0x55, 0xb8, 0x51, 0x75, 0xc7, 0xd0, 0xaa, 0xb2, 0xec, 0x02, 0x9a, 0x96,
	0x9f, 0xd0, 0x4a, 0x61, 0x99, 0xda, 0xb0, 0xc3, 0xd7, 0x95, 0x42, 0xd6, 0xdd, 0x8a, 0x5e, 0xf3,
	0x1b, 0xec, 0x0d, 0xa1, 0x3d, 0x46, 0x7a, 0x31, 0x4b, 0xfe, 0x7f, 0xc5, 0x29, 0xec, 0xe5, 0xc4,
	0xb5, 0xf1, 0x71, 0x43, 0x03, 0xbc, 0x5b, 0x68, 0x86, 0x98, 0x49, 0x9e, 0x58, 0x83, 0x3e, 0xb4,
	0x62, 0x29, 0xa6, 0xe9, 0x6c, 0x32, 0x4d, 0x33, 0x9c, 0x28, 0x4e, 0xf3, 0xd2, 0xe9, 0xc8, 0xcc,
	0x1f, 0xd3, 0x0c, 0x47, 0x9c, 0xe6, 0xde, 0x1d, 0xd4, 0x43, 0xcc, 0x97, 0x59, 0x11, 0x9a, 0x2f,
	0xe3, 0x18, 0x31, 0x29, 0x9e, 0xba, 0xa1, 0x85, 0x6b, 0x66, 0x81, 0x79, 0xce, 0x67, 0x58, 0xae,
	0x6f, 0xe1, 0xe0, 0xd3, 0x81, 0x56, 0xb9, 0xfb, 0x33, 0x17, 0x7c, 0xb6, 0x40, 0x41, 0xec, 0x0a,
	0x5c, 0xdb, 0x2a, 0x3b, 0xf9, 0xa3, 0xe3, 0x2e, 0xac, 0x87, 0x26, 0xd5, 0xdb, 0x61, 0xd7, 0x00,
	0x3f, 0x0d, 0xb0, 0x33, 0x23, 0xa8, 0x34, 0x52, 0x91, 0x04, 0xd0, 0x30, 0xf7, 0x0e, 0x8b, 0x63,
	0x58, 0xdb, 0xb0, 0xbf, 0x1a, 0xd8, 0x16, 0x44, 0xf5, 0xe2, 0xd7, 0xdc, 0x7c, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xcf, 0xa4, 0xd8, 0x67, 0x52, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetworkManagmentClient is the client API for NetworkManagment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkManagmentClient interface {
	SeedPeer(ctx context.Context, in *SeedPeerRequest, opts ...grpc.CallOption) (*Result, error)
	SetNetwork(ctx context.Context, in *SetNetworkRequest, opts ...grpc.CallOption) (*Result, error)
	ReloadConfig(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*Result, error)
}

type networkManagmentClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkManagmentClient(cc grpc.ClientConnInterface) NetworkManagmentClient {
	return &networkManagmentClient{cc}
}

func (c *networkManagmentClient) SeedPeer(ctx context.Context, in *SeedPeerRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.NetworkManagment/SeedPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkManagmentClient) SetNetwork(ctx context.Context, in *SetNetworkRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.NetworkManagment/SetNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkManagmentClient) ReloadConfig(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.NetworkManagment/ReloadConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkManagmentServer is the server API for NetworkManagment service.
type NetworkManagmentServer interface {
	SeedPeer(context.Context, *SeedPeerRequest) (*Result, error)
	SetNetwork(context.Context, *SetNetworkRequest) (*Result, error)
	ReloadConfig(context.Context, *ReloadRequest) (*Result, error)
}

// UnimplementedNetworkManagmentServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkManagmentServer struct {
}

func (*UnimplementedNetworkManagmentServer) SeedPeer(ctx context.Context, req *SeedPeerRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeedPeer not implemented")
}
func (*UnimplementedNetworkManagmentServer) SetNetwork(ctx context.Context, req *SetNetworkRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNetwork not implemented")
}
func (*UnimplementedNetworkManagmentServer) ReloadConfig(ctx context.Context, req *ReloadRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}

func RegisterNetworkManagmentServer(s *grpc.Server, srv NetworkManagmentServer) {
	s.RegisterService(&_NetworkManagment_serviceDesc, srv)
}

func _NetworkManagment_SeedPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkManagmentServer).SeedPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkManagment/SeedPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkManagmentServer).SeedPeer(ctx, req.(*SeedPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkManagment_SetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkManagmentServer).SetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkManagment/SetNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkManagmentServer).SetNetwork(ctx, req.(*SetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkManagment_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkManagmentServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkManagment/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkManagmentServer).ReloadConfig(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkManagment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NetworkManagment",
	HandlerType: (*NetworkManagmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeedPeer",
			Handler:    _NetworkManagment_SeedPeer_Handler,
		},
		{
			MethodName: "SetNetwork",
			Handler:    _NetworkManagment_SetNetwork_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _NetworkManagment_ReloadConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control/rpc/pb/core.proto",
}
