// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pb/core.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PeerBackend_BackendType int32

const (
	PeerBackend_UNKNOWN PeerBackend_BackendType = 0
	PeerBackend_TCP     PeerBackend_BackendType = 1
)

var PeerBackend_BackendType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TCP",
}

var PeerBackend_BackendType_value = map[string]int32{
	"UNKNOWN": 0,
	"TCP":     1,
}

func (x PeerBackend_BackendType) String() string {
	return proto.EnumName(PeerBackend_BackendType_name, int32(x))
}

func (PeerBackend_BackendType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{0, 0}
}

type Peer_State int32

const (
	Peer_ALIVE     Peer_State = 0
	Peer_SUSPECTED Peer_State = 1
	Peer_DEAD      Peer_State = 2
	Peer_NEW       Peer_State = 3
)

var Peer_State_name = map[int32]string{
	0: "ALIVE",
	1: "SUSPECTED",
	2: "DEAD",
	3: "NEW",
}

var Peer_State_value = map[string]int32{
	"ALIVE":     0,
	"SUSPECTED": 1,
	"DEAD":      2,
	"NEW":       3,
}

func (x Peer_State) String() string {
	return proto.EnumName(Peer_State_name, int32(x))
}

func (Peer_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{2, 0}
}

type RPC_Type int32

const (
	RPC_Request RPC_Type = 0
	RPC_Reply   RPC_Type = 1
	RPC_Error   RPC_Type = 2
)

var RPC_Type_name = map[int32]string{
	0: "Request",
	1: "Reply",
	2: "Error",
}

var RPC_Type_value = map[string]int32{
	"Request": 0,
	"Reply":   1,
	"Error":   2,
}

func (x RPC_Type) String() string {
	return proto.EnumName(RPC_Type_name, int32(x))
}

func (RPC_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{4, 0}
}

type PeerBackend struct {
	Type                 PeerBackend_BackendType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PeerBackend_BackendType" json:"type,omitempty"`
	Endpoint             string                  `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Priority             uint32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PeerBackend) Reset()         { *m = PeerBackend{} }
func (m *PeerBackend) String() string { return proto.CompactTextString(m) }
func (*PeerBackend) ProtoMessage()    {}
func (*PeerBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{0}
}

func (m *PeerBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerBackend.Unmarshal(m, b)
}
func (m *PeerBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerBackend.Marshal(b, m, deterministic)
}
func (m *PeerBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerBackend.Merge(m, src)
}
func (m *PeerBackend) XXX_Size() int {
	return xxx_messageInfo_PeerBackend.Size(m)
}
func (m *PeerBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerBackend.DiscardUnknown(m)
}

var xxx_messageInfo_PeerBackend proto.InternalMessageInfo

func (m *PeerBackend) GetType() PeerBackend_BackendType {
	if m != nil {
		return m.Type
	}
	return PeerBackend_UNKNOWN
}

func (m *PeerBackend) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *PeerBackend) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type OverlayPeer struct {
	VirtualIp            uint32   `protobuf:"varint,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	VirtualMask          uint32   `protobuf:"varint,2,opt,name=virtual_mask,json=virtualMask,proto3" json:"virtual_mask,omitempty"`
	IsRouter             bool     `protobuf:"varint,3,opt,name=is_router,json=isRouter,proto3" json:"is_router,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OverlayPeer) Reset()         { *m = OverlayPeer{} }
func (m *OverlayPeer) String() string { return proto.CompactTextString(m) }
func (*OverlayPeer) ProtoMessage()    {}
func (*OverlayPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{1}
}

func (m *OverlayPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OverlayPeer.Unmarshal(m, b)
}
func (m *OverlayPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OverlayPeer.Marshal(b, m, deterministic)
}
func (m *OverlayPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OverlayPeer.Merge(m, src)
}
func (m *OverlayPeer) XXX_Size() int {
	return xxx_messageInfo_OverlayPeer.Size(m)
}
func (m *OverlayPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_OverlayPeer.DiscardUnknown(m)
}

var xxx_messageInfo_OverlayPeer proto.InternalMessageInfo

func (m *OverlayPeer) GetVirtualIp() uint32 {
	if m != nil {
		return m.VirtualIp
	}
	return 0
}

func (m *OverlayPeer) GetVirtualMask() uint32 {
	if m != nil {
		return m.VirtualMask
	}
	return 0
}

func (m *OverlayPeer) GetIsRouter() bool {
	if m != nil {
		return m.IsRouter
	}
	return false
}

type Peer struct {
	PeerType             uint32         `protobuf:"varint,1,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	Version              uint64         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Details              *any.Any       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	State                Peer_State     `protobuf:"varint,8,opt,name=state,proto3,enum=pb.Peer_State" json:"state,omitempty"`
	StateVersion         uint32         `protobuf:"varint,9,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Region               string         `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Backend              []*PeerBackend `protobuf:"bytes,11,rep,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{2}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetPeerType() uint32 {
	if m != nil {
		return m.PeerType
	}
	return 0
}

func (m *Peer) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Peer) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Peer) GetState() Peer_State {
	if m != nil {
		return m.State
	}
	return Peer_ALIVE
}

func (m *Peer) GetStateVersion() uint32 {
	if m != nil {
		return m.StateVersion
	}
	return 0
}

func (m *Peer) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Peer) GetBackend() []*PeerBackend {
	if m != nil {
		return m.Backend
	}
	return nil
}

type PeerExchange struct {
	Peer                 []*Peer  `protobuf:"bytes,1,rep,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerExchange) Reset()         { *m = PeerExchange{} }
func (m *PeerExchange) String() string { return proto.CompactTextString(m) }
func (*PeerExchange) ProtoMessage()    {}
func (*PeerExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{3}
}

func (m *PeerExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerExchange.Unmarshal(m, b)
}
func (m *PeerExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerExchange.Marshal(b, m, deterministic)
}
func (m *PeerExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerExchange.Merge(m, src)
}
func (m *PeerExchange) XXX_Size() int {
	return xxx_messageInfo_PeerExchange.Size(m)
}
func (m *PeerExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerExchange.DiscardUnknown(m)
}

var xxx_messageInfo_PeerExchange proto.InternalMessageInfo

func (m *PeerExchange) GetPeer() []*Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type RPC struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 RPC_Type `protobuf:"varint,2,opt,name=type,proto3,enum=pb.RPC_Type" json:"type,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{4}
}

func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (m *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(m, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RPC) GetType() RPC_Type {
	if m != nil {
		return m.Type
	}
	return RPC_Request
}

func (m *RPC) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RPC) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *RPC) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Ping struct {
	Echo                 string   `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c2fbac20d44b7b4, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.PeerBackend_BackendType", PeerBackend_BackendType_name, PeerBackend_BackendType_value)
	proto.RegisterEnum("pb.Peer_State", Peer_State_name, Peer_State_value)
	proto.RegisterEnum("pb.RPC_Type", RPC_Type_name, RPC_Type_value)
	proto.RegisterType((*PeerBackend)(nil), "pb.PeerBackend")
	proto.RegisterType((*OverlayPeer)(nil), "pb.OverlayPeer")
	proto.RegisterType((*Peer)(nil), "pb.Peer")
	proto.RegisterType((*PeerExchange)(nil), "pb.PeerExchange")
	proto.RegisterType((*RPC)(nil), "pb.RPC")
	proto.RegisterType((*Ping)(nil), "pb.Ping")
}

func init() { proto.RegisterFile("proto/pb/core.proto", fileDescriptor_0c2fbac20d44b7b4) }

var fileDescriptor_0c2fbac20d44b7b4 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xdd, 0x6e, 0x9b, 0x4c,
	0x10, 0x0d, 0x18, 0xc7, 0x66, 0xb0, 0xf3, 0xa1, 0xfd, 0xa2, 0x8a, 0x26, 0xad, 0xe4, 0x92, 0x5e,
	0x38, 0x52, 0x85, 0xa5, 0xb4, 0x2f, 0x90, 0x3a, 0x5c, 0x44, 0x6d, 0x1d, 0x6b, 0xf3, 0x77, 0x69,
	0x81, 0x99, 0x38, 0xab, 0x50, 0xd8, 0x2e, 0xeb, 0xa8, 0x3c, 0x4b, 0x5f, 0xa0, 0xb7, 0x7d, 0xc3,
	0x6a, 0x07, 0x88, 0xac, 0x5e, 0x79, 0xce, 0x1c, 0x3c, 0xe7, 0xec, 0x99, 0x81, 0xff, 0xa5, 0x2a,
	0x75, 0x39, 0x93, 0xe9, 0x6c, 0x5d, 0x2a, 0x8c, 0x08, 0x31, 0x5b, 0xa6, 0x47, 0xaf, 0x37, 0x65,
	0xb9, 0xc9, 0x71, 0x46, 0x9d, 0x74, 0xfb, 0x30, 0x4b, 0x8a, 0xba, 0xa1, 0xc3, 0x5f, 0x16, 0x78,
	0x4b, 0x44, 0xf5, 0x39, 0x59, 0x3f, 0x61, 0x91, 0xb1, 0x19, 0x38, 0xba, 0x96, 0x18, 0x58, 0x13,
	0x6b, 0x7a, 0x70, 0x76, 0x1c, 0xc9, 0x34, 0xda, 0xa1, 0xa3, 0xf6, 0xf7, 0xa6, 0x96, 0xc8, 0xe9,
	0x43, 0x76, 0x04, 0x43, 0x2c, 0x32, 0x59, 0x8a, 0x42, 0x07, 0xf6, 0xc4, 0x9a, 0xba, 0xfc, 0x05,
	0x1b, 0x4e, 0x2a, 0x51, 0x2a, 0xa1, 0xeb, 0xa0, 0x37, 0xb1, 0xa6, 0x63, 0xfe, 0x82, 0xc3, 0x13,
	0xf0, 0x76, 0x86, 0x31, 0x0f, 0x06, 0xb7, 0x8b, 0x2f, 0x8b, 0xab, 0xfb, 0x85, 0xbf, 0xc7, 0x06,
	0xd0, 0xbb, 0x99, 0x2f, 0x7d, 0x2b, 0xcc, 0xc1, 0xbb, 0x7a, 0x46, 0x95, 0x27, 0xb5, 0x31, 0xc1,
	0xde, 0x02, 0x3c, 0x0b, 0xa5, 0xb7, 0x49, 0xbe, 0x12, 0x92, 0x2c, 0x8e, 0xb9, 0xdb, 0x76, 0x2e,
	0x25, 0x7b, 0x07, 0xa3, 0x8e, 0xfe, 0x9e, 0x54, 0x4f, 0x64, 0x67, 0xcc, 0xbd, 0xb6, 0xf7, 0x2d,
	0xa9, 0x9e, 0xd8, 0x31, 0xb8, 0xa2, 0x5a, 0xa9, 0x72, 0xab, 0x51, 0x91, 0xa5, 0x21, 0x1f, 0x8a,
	0x8a, 0x13, 0x0e, 0xff, 0xd8, 0xe0, 0x90, 0xce, 0x31, 0xb8, 0x12, 0x51, 0xad, 0x5e, 0x92, 0x30,
	0xc6, 0x11, 0x15, 0x39, 0x0d, 0x60, 0xf0, 0x8c, 0xaa, 0x12, 0x65, 0x41, 0x02, 0x0e, 0xef, 0x20,
	0x8b, 0x60, 0x90, 0xa1, 0x4e, 0x44, 0x5e, 0xd1, 0x68, 0xef, 0xec, 0x30, 0x6a, 0x82, 0x8f, 0xba,
	0xe0, 0xa3, 0xf3, 0xa2, 0xe6, 0xdd, 0x47, 0xec, 0x3d, 0xf4, 0x2b, 0x9d, 0x68, 0x0c, 0x86, 0x14,
	0xf6, 0x41, 0x17, 0x76, 0x74, 0x6d, 0xba, 0xbc, 0x21, 0xd9, 0x09, 0x8c, 0xa9, 0x58, 0x75, 0xaa,
	0x2e, 0x19, 0x1a, 0x51, 0xf3, 0xae, 0x95, 0x7e, 0x05, 0xfb, 0x0a, 0x37, 0x86, 0x05, 0xda, 0x41,
	0x8b, 0xd8, 0x29, 0x0c, 0xd2, 0x26, 0xe5, 0xc0, 0x9b, 0xf4, 0xa6, 0xde, 0xd9, 0x7f, 0xff, 0x6c,
	0x94, 0x77, 0x7c, 0xf8, 0x09, 0xfa, 0xa4, 0xcb, 0x5c, 0xe8, 0x9f, 0x7f, 0xbd, 0xbc, 0x8b, 0xfd,
	0x3d, 0x36, 0x06, 0xf7, 0xfa, 0xf6, 0x7a, 0x19, 0xcf, 0x6f, 0xe2, 0x0b, 0xdf, 0x62, 0x43, 0x70,
	0x2e, 0xe2, 0xf3, 0x0b, 0xdf, 0x36, 0x1b, 0x5a, 0xc4, 0xf7, 0x7e, 0x2f, 0xfc, 0x00, 0x23, 0x33,
	0x2d, 0xfe, 0xb9, 0x7e, 0x4c, 0x8a, 0x0d, 0xb2, 0x37, 0xe0, 0x98, 0xa4, 0x02, 0x8b, 0xd4, 0x86,
	0x9d, 0x1a, 0xa7, 0x6e, 0xf8, 0xdb, 0x82, 0x1e, 0x5f, 0xce, 0xd9, 0x01, 0xd8, 0x22, 0x6b, 0x93,
	0xb5, 0x45, 0xc6, 0x26, 0xed, 0xd5, 0xd9, 0x14, 0xc4, 0xc8, 0xfc, 0x8b, 0x2f, 0xe7, 0xd1, 0xce,
	0x99, 0x1d, 0x42, 0x1f, 0x95, 0x2a, 0x9b, 0xa5, 0xb9, 0xbc, 0x01, 0xe6, 0xc0, 0x1e, 0xb6, 0xc5,
	0x5a, 0x9b, 0x87, 0x3b, 0xcd, 0xf1, 0x75, 0x98, 0x31, 0x70, 0xb2, 0x44, 0x27, 0x41, 0x7f, 0x62,
	0x4d, 0x47, 0x9c, 0xea, 0xf0, 0x14, 0x9c, 0xee, 0xda, 0x38, 0xfe, 0xd8, 0x62, 0xa5, 0xfd, 0x3d,
	0xf3, 0x5e, 0x8e, 0x32, 0xaf, 0x7d, 0xcb, 0x94, 0xb1, 0x19, 0xec, 0xdb, 0xe1, 0x11, 0x38, 0x4b,
	0x51, 0x6c, 0xcc, 0x18, 0x5c, 0x3f, 0x96, 0x64, 0xd6, 0xe5, 0x54, 0xa7, 0xfb, 0xb4, 0xcf, 0x8f,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x79, 0x9f, 0x91, 0x02, 0x71, 0x03, 0x00, 0x00,
}
