// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tcp.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TCPPeerDetail struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TCPPeerDetail) Reset()         { *m = TCPPeerDetail{} }
func (m *TCPPeerDetail) String() string { return proto.CompactTextString(m) }
func (*TCPPeerDetail) ProtoMessage()    {}
func (*TCPPeerDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ad0def2cb03577c, []int{0}
}

func (m *TCPPeerDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TCPPeerDetail.Unmarshal(m, b)
}
func (m *TCPPeerDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TCPPeerDetail.Marshal(b, m, deterministic)
}
func (m *TCPPeerDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TCPPeerDetail.Merge(m, src)
}
func (m *TCPPeerDetail) XXX_Size() int {
	return xxx_messageInfo_TCPPeerDetail.Size(m)
}
func (m *TCPPeerDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TCPPeerDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TCPPeerDetail proto.InternalMessageInfo

func (m *TCPPeerDetail) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*TCPPeerDetail)(nil), "proto.TCPPeerDetail")
}

func init() { proto.RegisterFile("proto/tcp.proto", fileDescriptor_9ad0def2cb03577c) }

var fileDescriptor_9ad0def2cb03577c = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x49, 0x2e, 0xd0, 0x03, 0xb3, 0x84, 0x58, 0xc1, 0x94, 0x92, 0x32, 0x17, 0x6f,
	0x88, 0x73, 0x40, 0x40, 0x6a, 0x6a, 0x91, 0x4b, 0x6a, 0x49, 0x62, 0x66, 0x8e, 0x90, 0x10, 0x17,
	0x4b, 0x41, 0x7e, 0x51, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x98, 0x9d, 0xc4, 0x06,
	0x56, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x4c, 0xf0, 0x74, 0x45, 0x00, 0x00, 0x00,
}
